config/routes.rb
Rails.application.routes.draw do






  mount ActionCable.server => '/cable'



  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  authenticated :user do
    get 'new_navigator' , to: "navigators#create_user" , as: 'create_navigator'
    post 'new_navigator' , to: "navigators#create_user"


  resources :conditions
  resources :lists
  resources :offers
  resources :students
  resources :users, except: [:show]
  resources :profiles , except: [:new,:edit,:show,:index]
  resources :engineers
  resources :areas
  resources :designations
  resources :modalities
  resources :companies
  resources :items
  resources :types
  resources :themes
  resources :concepts
  resources :responsible_functions
  resources :workers
  resources :admin_controls do
    resources :lists
    resources :checklists do
      resources :checklist_items
    end
  end

    get '/create_items', to: 'lists#create_items'
    post '/create_items' ,to: 'lists#create_items' , as: "create_lists"

    get '/destroy_engineer'  , to: 'designations#destroy_engineer' ,as: 'destroy_engineer'
    post '/destroy_engineer'  , to: 'designations#destroy_engineer'

    get '/destroy_support'  , to: 'admin_controls#destroy_support' ,as: 'destroy_support'
    post '/destroy_support'  , to: 'admin_controls#destroy_support'

    get '/destroy_manager'  , to: 'admin_controls#destroy_manager' ,as: 'destroy_manager'
    post '/destroy_manager'  , to: 'admin_controls#destroy_manager'

  resources :titles
  resources :universities
  resources :register_books
  get "/register_offer" , to: 'register_books#index_offer'  ,as: 'register_books_offer'


  resources :states do
    collection { post :import }
  end

  resources :cities do
    collection { post :import }
  end



  end

  get ":url" => "application#redirect_user", :constraints => { :url => /.*/ }

end

app/models/area.rb
class Area < ApplicationRecord
end

app/models/checklist.rb
class Checklist < ApplicationRecord
  belongs_to :admin_control
  has_many :checklist_items , dependent: :destroy


  def new_item
   checklist_items.build
  end

  def percent_complete
    #return 0 #if total_items == 0
    #((checklist_items.select(&:complete?).count.to_f / total_items)*100).round
  end
  def percent_in_progress
    50
  end

  def total_items
    @total_items ||= checklist_items.count
  end

end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
  require 'csv'
  def  self.import(file)
    CSV.foreach(file.path, headers:true) do |row|
      City.create! row.to_hash
    end
  end
end

app/models/company.rb
class Company < ApplicationRecord
  validates :name, presence: true
  validates :identification, presence: true , numericality: true
  validates :phone, presence: true
  validates :address, presence: true
  validates :email, presence: true ,  format: { with: /\A\S+@.+\.\S+\z/ ,message: "Direccion valida con @" }
end

app/models/concept.rb
class Concept < ApplicationRecord
  validates  :name, presence: true
end

app/models/condition.rb
class Condition < ApplicationRecord
end

app/models/engineer.rb
class Engineer < ApplicationRecord
  belongs_to :profile
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name , presence: true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :admin_control


  def completed?
    completed == true
  end
end

app/models/modality.rb
class Modality < ApplicationRecord
  validates :name,:description,presence: true

end

app/models/offer.rb
class Offer < ApplicationRecord
  scope :by_month, lambda {|date| where('publication_date >= ? AND publication_date <=  ?', date.beginning_of_month, date.end_of_month)}
  belongs_to :worker
  belongs_to :modality
  belongs_to :city, optional: true
  belongs_to :company, optional: true
  belongs_to :user


  validates :code,:worker_id,:modality_id, :status, :publication_date, presence: true
  validates :date_submission_obs, :date_offer_evaluation_report,:date_deadline_submission_offers,
            :date_obs_offer_evaluation_report,:date_publication_observations_report,:date_acceptance_offers,presence: true
  validates :status_obs_offer_evaluation_report,:status_offer_evaluation_report,:status_obs_report,
            :status_acceptance_offers,:status_submission_offers,:status_obs , presence: true
  validates :presented_value,:budget_value, :company_id, :city_id, :official_page,:email_company,
            :email_alternative,:link_document,presence: true

  #solo date y status
  has_rich_text :object



  def self.STATUS
    [["En proceso","En proceso"],["Descartado","Descartado"],["Adjudicado","Adjudicado"],["Entregado","Entregado"]].sort
  end

  def self.STATUS_YES_OR_NOT
    [["Si","Si"],["No","No"]]
  end






end

app/models/process.rb
class Process < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :name, presence: true
  validates :profile_type, presence: true

  def self.PROFILE_TYPE
    [["Lider",1],["Ingeniero Encargado",2],["Ingeniero acompañante",3],
     ["Responsable",4],["Apoyo",5],["Comodin",6],
     ["Practicante",7],["Empleado",8],["Ingeniero",9]]
  end


  def self.PROFILE_LEADER
    1
  end
  def self.PROFILE_ENGINEER_IN_CHARGE
    2
  end
  def self.PROFILE_ENGINEER_ATTENDANT
    3
  end
  def self.RESPONSIBLE
    4
  end
  def self.SUPPORT
    5
  end
  def self.WILDCARD
    6
  end
  def self.INTERN
    7
  end
  def self.EMPLOYEE
    8
  end
  def self.ENGINEER
    9
  end


end

app/models/state.rb
class State < ApplicationRecord
  require 'csv'
  def  self.import(file)
    CSV.foreach(file.path, headers:true) do |row|
      State.create! row.to_hash
    end
  end

end

app/models/student.rb
class Student < ApplicationRecord


  belongs_to :condition
  belongs_to :type_identification
  belongs_to :city
  belongs_to :university
  belongs_to :title
=begin



  belongs_to :title



  validates :name, :last_name,:phone,:address,:score,:semester,presence:true
  validates :semester,:career,:comment,:age,:birthday, presence:true
  validates :link_data,:issued_in,:link_university ,presence:true
  validates :leader_first,:leader_second, presence: true
  validates :identification,presence: true,numericality: true
  validates :mail, presence: true , format: { with: /\A\S+@.+\.\S+\z/ ,message: "Direccion valida con @" }

=end
  has_rich_text :body_1
  has_rich_text :body_2


end

app/models/theme.rb
class Theme < ApplicationRecord
  validates :name, presence: true
end

app/models/title.rb
class Title < ApplicationRecord
end

app/models/type.rb
class Type < ApplicationRecord
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  def self.ADMINISTRATOR
    1
  end
  def self.EDITOR
    2
  end
  def self.AUTHOR
    3
  end

  def show_name_role(role)
    if role == User.ADMINISTRATOR
      "Administrador"
    elsif role == User.EDITOR
      "Editor"
    elsif role == User.AUTHOR
      "Usuario"
    end
  end


  def destroy
    update_attributes(deactivated: true) unless deactivated
  end

  def active_for_authentication?
    super && !deactivated
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


end

app/models/worker.rb
class Worker < ApplicationRecord

  belongs_to :type_identification

  validates :first_name,:last_name,:phone,:phone_2, presence: true
  validates :identification, presence: true,numericality: true
  validates :type_identification_id, presence: true
  validates :email, presence: true ,  format: { with: /\A\S+@.+\.\S+\z/ ,message: "Direccion valida con @" }

  has_rich_text :function

  def full_name
    self.first_name + " " + self .last_name
  end

  def self.CHARACTERISTIC_TWO
    0
  end
  def self.CHARACTERISTIC_THREE
    1
  end
  def self.CHARACTERISTIC_FOUR
    2
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/shared/_nav.html.erb
<div class="vertical-nav bg-white" id="sidebar">
  <div class="py-4 px-3 mb-4 bg-light">
    <div class="media d-flex align-items-center"><img src="https://res.cloudinary.com/mhmd/image/upload/v1556074849/avatar-1_tcnd60.png" alt="..." width="65" class="mr-3 rounded-circle img-thumbnail shadow-sm">
      <div class="media-body">
        <h4 class="m-0">Bienvenido</h4>
        <p class="font-weight-light text-muted mb-0">Control y seguimiento</p>
      </div>
    </div>
  </div>

  <p class="text-gray font-weight-bold text-uppercase px-3 small pb-4 mb-0">Main</p>

  <ul class="nav flex-column bg-white mb-0">

    <li class="nav-header mb-0 nav-item">
      <a class="nav-link text-dark font-italic bg-light" data-toggle="collapse" href="#ui-designations" aria-expanded="false" aria-controls="ui-designations">
        <span class="sm-icons-fa"> </span>
        <i class="fa fa-th-large mr-3 text-primary fa-fw"></i><span class="menu-title ">Designacion actividades y </span><span class="pl-3">responsables</span>
      </a>


      <div class="collapse" id="ui-designations">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item"><a class="nav-link text-dark font-italic bg-light" href="<%= designations_path %>"><i class="fa fa-th-large mr-4 text-primary fa-fw"></i><span>Lista de Actividades</span></a></li>
          <li class="nav-item"><a class="nav-link text-dark font-italic bg-light" href="<%= new_designation_path %>"><i class="fa fa-th-large mr-4 text-primary fa-fw"></i><span>Nuevo Actividad</span></a></li>
        </ul>
      </div>
    </li>


    <li class="nav-header mb-0 nav-item">
      <a class="nav-link text-dark font-italic bg-light" data-toggle="collapse" href="#ui-company" aria-expanded="false" aria-controls="ui-company">
        <span class="sm-icons-fa"> </span>
        <i class="fa fa-th-large mr-3 text-primary fa-fw"></i><span class="menu-title ">Entidades</span>
      </a>


      <div class="collapse" id="ui-company">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item"><a class="nav-link text-dark font-italic bg-light" href="<%= companies_path %>"><i class="fa fa-th-large mr-4 text-primary fa-fw"></i><span>Lista de Entidades</span></a></li>
        </ul>
      </div>
    </li>

    <li class="nav-header mb-0 nav-item">
      <a class="nav-link text-dark font-italic bg-light" data-toggle="collapse" href="#ui-engineers" aria-expanded="false" aria-controls="ui-engineers">
        <span class="sm-icons-fa"> </span>
        <i class="fa fa-th-large mr-3 text-primary fa-fw"></i><span class="menu-title ">Ingenieros</span>
      </a>


      <div class="collapse" id="ui-engineers">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item"><a class="nav-link text-dark font-italic bg-light" href="<%= engineers_path %>"><i class="fa fa-th-large mr-4 text-primary fa-fw"></i><span>Lista de ingenieros</span></a></li>
          <li class="nav-item"><a class="nav-link text-dark font-italic bg-light" href="<%= new_engineer_path %>"><i class="fa fa-th-large mr-4 text-primary fa-fw"></i><span>Nuevo ingenieros</span></a></li>
        </ul>
      </div>
    </li>

    <li class="nav-header mb-0 nav-item">
      <a class="nav-link text-dark font-italic bg-light" data-toggle="collapse" href="#ui-settings" aria-expanded="false" aria-controls="ui-settings">
        <span class="sm-icons-fa"> </span>
        <i class="fa fa-th-large mr-3 text-primary fa-fw"></i><span class="menu-title ">Configuración</span>
      </a>


      <div class="collapse" id="ui-settings">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item"><a class="nav-link text-dark font-italic bg-light" href="<%= profiles_path %>"><i class="fa fa-th-large mr-4 text-primary fa-fw"></i><span>Perfiles</span></a></li>
          <li class="nav-item"><a class="nav-link text-dark font-italic bg-light" href="<%= areas_path %>"><i class="fa fa-th-large mr-4 text-primary fa-fw"></i><span>Areas</span></a></li>
          <li class="nav-item"><a class="nav-link text-dark font-italic bg-light" href="<%= modalities_path %>"><i class="fa fa-th-large mr-4 text-primary fa-fw"></i><span>Modalidades</span></a></li>
          <li class="nav-item"><a class="nav-link text-dark font-italic bg-light" href="<%= types_path %>"><i class="fa fa-th-large mr-4 text-primary fa-fw"></i><span>Tipos</span></a></li>

          <li class="nav-item">
            <a style="padding-left: 22px" class="nav-link text-dark font-italic bg-light" data-toggle="collapse" href="#ui-s-admin" aria-expanded="false" aria-controls="ui-s-admin">
              <span class="sm-icons-fa"> </span>
              <i class="fa fa-th-large mr-3 text-primary fa-fw"></i><span class="menu-title ">Seguimiento Administrador</span>
            </a>

            <div class="collapse" id="ui-s-admin">
              <ul class="nav flex-column sub-menu">
                <li class="nav-item"><a style="font-size: 15px; padding-left:22px" class="nav-link text-dark font-italic bg-light" href="<%= items_path %>"><i class="fa fa-th-large mr-4 text-primary fa-fw"></i><span>Item especificos</span></a></li>
              </ul>
            </div>

          </li>

        </ul>
      </div>
    </li>










    <li class="nav-header mb-0 nav-item">
      <a class="nav-link text-dark font-italic bg-light" data-toggle="collapse" href="#ui-leader" aria-expanded="false" aria-controls="ui-leader">
        <span class="sm-icons-fa"> </span>
        <i class="fa fa-th-large mr-3 text-primary fa-fw"></i><span class="menu-title ">Empleados</span>
      </a>


      <div class="collapse" id="ui-leader">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item"><a class="nav-link text-dark font-italic bg-light" href="<%= workers_path %>"><i class="fa fa-th-large mr-4 text-primary fa-fw"></i><span>Lista de Empleado</span></a></li>
          <li class="nav-item"><a class="nav-link text-dark font-italic bg-light" href="<%= new_worker_path %>"><i class="fa fa-th-large mr-4 text-primary fa-fw"></i><span>Nuevo Empleado</span></a></li>
        </ul>
      </div>
    </li>

    <li class="nav-header mb-0 nav-item">
      <a class="nav-link text-dark font-italic bg-light" data-toggle="collapse" href="#ui-responsible" aria-expanded="false" aria-controls="ui-responsible">
        <span class="sm-icons-fa"> </span>
        <i class="fa fa-th-large mr-3 text-primary fa-fw"></i><span class="menu-title ">Rol Responsable</span>
      </a>


      <div class="collapse" id="ui-responsible">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item"><a class="nav-link text-dark font-italic bg-light" href="<%= responsible_functions_path %>"><i class="fa fa-th-large mr-4 text-primary fa-fw"></i><span>Lista de Roles Responsable</span></a></li>
          <li class="nav-item"><a class="nav-link text-dark font-italic bg-light" href="<%= new_responsible_function_path %>"><i class="fa fa-th-large mr-4 text-primary fa-fw"></i><span>Nuevo Rol Responsable</span></a></li>
        </ul>
      </div>
    </li>

    <li class="nav-header mb-0 nav-item">
      <a class="nav-link text-dark font-italic bg-light" data-toggle="collapse" href="#ui-theme" aria-expanded="false" aria-controls="ui-theme">
        <span class="sm-icons-fa"> </span>
        <i class="fa fa-th-large mr-3 text-primary fa-fw"></i><span class="menu-title ">Asuntos</span>
      </a>


      <div class="collapse" id="ui-theme">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item"><a class="nav-link text-dark font-italic bg-light" href="<%= themes_path %>"><i class="fa fa-th-large mr-4 text-primary fa-fw"></i><span>Lista de Asuntos</span></a></li>
          <li class="nav-item"><a class="nav-link text-dark font-italic bg-light" href="<%= new_theme_path %>"><i class="fa fa-th-large mr-4 text-primary fa-fw"></i><span>Nuevo Asuntos</span></a></li>
        </ul>
      </div>
    </li>

  </ul>
</div>

app/views/layouts/shared/_nav_two.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="#"><%= image_tag "ciglop.png" %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarScroll">


    <ul class="navbar-nav mr-auto my-2 my-lg-0 navbar-nav-scroll" style="max-height: 100px;">


      <% if user_signed_in? %>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="licitation" role="button" data-toggle="dropdown" aria-expanded="false">
            Segto licitaciones
          </a>
          <ul class="dropdown-menu" aria-labelledby="licitation">
            <li><a class="dropdown-item" href="<%= offers_path %>">Lista de licitaciones</a></li>
            <li><a class="dropdown-item" href="<%= new_offer_path %>">Nuevo licitacion</a></li>
          </ul>
        </li>


      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="Companies" role="button" data-toggle="dropdown" aria-expanded="false">
          Segto Admin
        </a>
        <ul class="dropdown-menu" aria-labelledby="Companies">
          <li><a class="dropdown-item" href="<%= admin_controls_path %>">Lista de Seguimientos</a></li>
          <li><a class="dropdown-item" href="<%= new_admin_control_path %>">Nuevo Seguimiento</a></li>
        </ul>
      </li>


        <% if current_user.role_id == User.ADMINISTRATOR  || current_user.role_id == User.EDITOR %>
           <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="Companies" role="button" data-toggle="dropdown" aria-expanded="false">
        Entidades
        </a>
        <ul class="dropdown-menu" aria-labelledby="Companies">
          <li><a class="dropdown-item" href="<%= companies_path %>">Lista de entidades</a></li>
          <li><a class="dropdown-item" href="<%= new_company_path %>">Nuevo entidad</a></li>
        </ul>
      </li>
        <% end %>


        <% if current_user.role_id == User.ADMINISTRATOR  or  current_user.role_id == User.EDITOR %>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="students" role="button" data-toggle="dropdown" aria-expanded="false">
          Practicantes
          </a>
          <ul class="dropdown-menu" aria-labelledby="students">
            <li><a class="dropdown-item" href="<%= students_path %>">Lista de Practicante</a></li>
            <li><a class="dropdown-item" href="<%= conditions_path %>">Estados de los estudiantes</a></li>
            <li><a class="dropdown-item" href="<%= universities_path %>">Universidades</a></li>
            <li><a class="dropdown-item" href="<%= titles_path %>">Grado academico</a></li>


          </ul>
        </li>
        <% end %>

        <% if current_user.role_id == User.ADMINISTRATOR  or  current_user.role_id == User.EDITOR %>
           <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="Workers" role="button" data-toggle="dropdown" aria-expanded="false">
          Empleados
        </a>
        <ul class="dropdown-menu" aria-labelledby="Workers">
          <li><a class="dropdown-item" href="<%= workers_path %>">Lista de Empleados</a></li>
          <li><a class="dropdown-item" href="<%= new_worker_path %>">Nuevo Empleados</a></li>
        </ul>
      </li>
        <% end %>

        <% if current_user.role_id == User.ADMINISTRATOR || current_user.role_id == User.EDITOR %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="settings" role="button" data-toggle="dropdown" aria-expanded="false">
          Configuración
        </a>

        <ul class="dropdown-menu" aria-labelledby="settings">
          <li><a class="dropdown-item" href="<%= themes_path %>">Asuntos</a>
          <li><a class="dropdown-item" href="<%= concepts_path %>">Conceptos</a></li>
          <li><a class="dropdown-item" href="<%= items_path %>">Items Especificos</a></li>
          <li><a class="dropdown-item" href="<%= modalities_path %>">Modalidad</a></li>
          <li><a class="dropdown-item" href="<%=  responsible_functions_path %>">Rol Responsable</a></li>
          <li><a class="dropdown-item" href="<%= types_path %>">Tipos</a> </li>

        </ul>
      </li>
          <% end %>


        <% if current_user.role_id == User.ADMINISTRATOR %>
       <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="settings" role="button" data-toggle="dropdown" aria-expanded="false">
          G.U.R
        </a>

        <ul class="dropdown-menu" aria-labelledby="settings">
          <li><a class="dropdown-item" href="<%= users_path %>">Usuarios</a>
          <li><a class="dropdown-item" href="<%= new_navigator_path %>">Nuevo usuario</a> </li>
          <li><a class="dropdown-item" href="<%= register_books_path %>">Registro Sgto. Admin</a> </li>
          <li><a class="dropdown-item" href="<%= register_books_offer_path %>">Registro Sgto. Licitaciones</a> </li>

        </ul>
      </li>
      <% end %>


<% end %>
    </ul>




    <form class="d-flex" style="">
      <div class="dropdown">
        <div class="btn-group">
          <div class="btn-group dropleft" role="group">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user"></i>
        </button>
        <div class="dropdown-menu">
          <% unless user_signed_in? %>
          <%= link_to "Iniciar Sesion", "/users/sign_in" , class: "form-control" %>
          <% end %>
          <% if user_signed_in? %>
            <h6 class="dropdown-header" ><%= current_user.email %></h6>
            <%= link_to "Cambiar contraseña",edit_user_registration_path(current_user.id) , class:"dropdown-item" %>
            <%= link_to "Cerrar sesion", destroy_user_session_path , method: :delete , class:"dropdown-item"%>
          <% end %>
      </div>
          </div>
        </div>



      </div>
    </form>
  </div>
</nav>

app/views/layouts/shared/_notice.html.erb
<div class="flash-message" style="margin-bottom: 40px;">
  <% flash.each do |name, msg|
    alert = case name
            when "alert", "error"
              "danger"
            when "notice", "success"
              "success"
            else
              "primary"
            end
  %>
    <div class="alert alert-<%=alert%> alert-dismissible text-center" >
      <strong> <%= msg%> </strong>
    </div>
  <% end %>
</div>