config/routes.rb
Rails.application.routes.draw do






  mount ActionCable.server => '/cable'



  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  authenticated :user do
    get 'new_navigator' , to: "navigators#create_user" , as: 'create_navigator'
    post 'new_navigator' , to: "navigators#create_user"


  resources :conditions
  resources :lists
  resources :offers
  resources :students
  resources :users, except: [:show]
  resources :profiles , except: [:new,:edit,:show,:index]
  resources :engineers
  resources :areas
  resources :designations
  resources :modalities
  resources :companies
  resources :items
  resources :types
  resources :themes
  resources :concepts
  resources :responsible_functions
  resources :workers
  resources :admin_controls do
    resources :lists
    resources :checklists do
      resources :checklist_items
    end
  end

    get '/create_items', to: 'lists#create_items'
    post '/create_items' ,to: 'lists#create_items' , as: "create_lists"

    get '/destroy_engineer'  , to: 'designations#destroy_engineer' ,as: 'destroy_engineer'
    post '/destroy_engineer'  , to: 'designations#destroy_engineer'

    get '/destroy_support'  , to: 'admin_controls#destroy_support' ,as: 'destroy_support'
    post '/destroy_support'  , to: 'admin_controls#destroy_support'

    get '/destroy_manager'  , to: 'admin_controls#destroy_manager' ,as: 'destroy_manager'
    post '/destroy_manager'  , to: 'admin_controls#destroy_manager'

  resources :titles
  resources :universities
  resources :register_books
  get "/register_offer" , to: 'register_books#index_offer'  ,as: 'register_books_offer'


  resources :states do
    collection { post :import }
  end

  resources :cities do
    collection { post :import }
  end



  end

  get ":url" => "application#redirect_user", :constraints => { :url => /.*/ }

end

app/models/company.rb
class Company < ApplicationRecord
  validates :name, presence: true
  validates :identification, presence: true , numericality: true
  validates :phone, presence: true
  validates :address, presence: true
  validates :email, presence: true ,  format: { with: /\A\S+@.+\.\S+\z/ ,message: "Direccion valida con @" }
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[ show edit update destroy ]
  include Deleteable

  def index
    @search = params[:search] || ""

    if @search.present?
    @companies = Company.where("(LOWER(name) like LOWER(?) OR LOWER(identification) like LOWER(?)) " ,"%#{@search}%","%#{@search}%")
                     .order('name').paginate(page: params[:page], per_page: 30).order('id desc')
    else
      @companies = Company.all.paginate(page: params[:page], per_page: 30).order('id desc')
    end
  end


  def show
  end


  def new
    @company = Company.new
  end


  def edit
  end


  def create
    @company = Company.new(company_params)
    if @company.save
       redirect_to @company, notice: "Company was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
  end


  def update
    @enable = params[:enable]
    @enable ? @company.enable = @enable: @company.enable = false
      if @company.update(company_params)
         redirect_to @company, notice: "Company was successfully updated."
      else
       render :edit, status: :unprocessable_entity
      end
  end


  def destroy
    delete_with_references(@companies,companies_path)
  end

  private

    def set_company
      @company = Company.find(params[:id])
    end

    def company_params
      params.require(:company).permit(:name,:identification,:enable,:address,:phone,:email)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<div class="row">
  <div class="offset-sm-2 col-sm-8">
    <div class="card card-margin">

      <div class="card-header">
        <% route = "companies" %>
        <%= render "layouts/views_partials/link_to_back" , route: route  %>
      </div>

      <%= bootstrap_form_with(model: company, local: true, html: { class: "forms-sample needs-validation", novalidate: true }) do |form| %>
        <div class="card-body">
          <% if company.errors.any? %>
            <div id="error_explanation" style="display: none">
              <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

              <ul>
                <% company.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>


          <div class="form-group">
            <%= form.text_field :identification, label: t('company.identification'), class: "form-control" , required: true %>
          </div>

          <div class="form-group">
            <%= form.text_field :name, label: t('company.name') ,class: "form-control" , required: true %>
          </div>

          <div class="form-group">
            <div class="row no-gutters">
              <div class="col-lg-6 pr-2">
                <%= form.text_field :phone,label: t('company.phone') ,  class: "form-control" %>
              </div>
              <div class="col-lg-6">
                <%= form.email_field :email,label: t('company.email') , class: "form-control"  %>
              </div>
            </div>

          </div>

          <div class="form-group">
              <%= form.text_field :address, label: t('company.address') , class: "form-control" %>
          </div>


          <% if @company.id? %>
            <div class="form-group d-flex justify-content-center">
              <div><label for=""> Habilitado / inhabilitado </label> </div>
            </div>
            <div class="form-group d-flex justify-content-center">

               <label class="switch">
                <input type="checkbox" name="enable" id="enable" value="true" <%= @company.enable ? "checked='checked'":""%> >
                <span class="slider round"></span>
              </label>
            </div>
          <% end %>






        <div class="card-footer bg-white">
          <button type="submit" class="btn btn-primary mr-2 btn-action">Guardar</button>
          <%= link_to 'Regresar', companies_path ,class: "btn btn-light btn-action"  %>

        </div>


        </div>
        </div>
        </div>
        </div>
      <% end %>

app/views/companies/edit.html.erb
<%  if current_user.role_id == User.ADMINISTRATOR  || current_user.role_id == User.EDITOR %>

<div class="row">
  <div class="col-sm-10 offset-sm-1  text-center">
    <h3 class="my-4">Editar compañia</h3>
  </div>
</div>
<%= render 'form', company: @company %>


<% else %>

<% route = "companies" %>
<%= render "layouts/views_partials/not_found", route: route %>
<% end %>

app/views/companies/index.html.erb
<%  if current_user.role_id == User.ADMINISTRATOR  || current_user.role_id == User.EDITOR %>
<div class="row">
  <div class="col-md-10 offset-md-1  text-center">
    <h2 class="my-4">Entidad</h2>
  </div>
</div>
<div class="row">
  <div class="col-md-8 offset-2  text-left">
    <form>
      <div class="form-row my-4">
        <div style="width: 80%; display: inline-block">
        <input name="search" placeholder="<%= t('workers.first_name') %>" value="<%=@search%>" class="form-control py-1"/>
        </div>
        <div style="display: inline-block; width: 10%">
          <button type="submit" value="<%= t('action.search') %>" style="margin-top: 4px; margin-left: 4px;" class="btn btn-outline-primary btn-sm py-1">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>
  </div>
</div>

<div class="row">
  <div class="col-md-10 offset-md-1">
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
        <tr>
          <th scope="col" class="text-center">Nombre</th>
          <th scope="col" class="text-center">Identificación</th>
          <th scope="col" class="text-center">Telefono</th>
          <th scope="col" class="text-center">Dirección</th>
          <th scope="col" class="text-center"></th>
        </tr>
        </thead>

        <tbody>
        <% @companies.each_with_index  do |company| %>

          <tr>
            <td class="text-center"><%= company.name %></td>
            <td class="text-center"><%= company.identification %></td>
            <td class="text-center"><%= company.phone %></td>
            <td class="text-center"><%= company.address %></td>
            <td class="text-center">
              <%  if current_user.role_id == User.ADMINISTRATOR  || current_user.role_id == User.EDITOR %>
                 <%= link_to company_path(company) do %>
                  <span class="btn btn-sm btn-outline-success"> <i class="far fa-eye"></i> </span>
                 <% end %>
                 <%= link_to edit_company_path(company) do %>
                   <span class="btn btn-sm btn-outline-primary"> <i class="far fa-edit"></i> </span>
                <% end  %>
                <% end %>
              <%  if current_user.role_id == User.ADMINISTRATOR %>
                 <%= link_to  company, method: :delete, data: { confirm: '¿Esta seguro que desea eliminarlo?' } do %>
                    <span class="btn btn-sm btn-outline-danger">  <i class="fas fa-trash-alt"></i> </span>
                 <% end %>
              <% end %>

            </td>
          </tr>
        <% end %>
        </tbody>
      </table>

      <br>
    </div>

    <div class="will_paginate">
      <%= will_paginate(@companies, :renderer => WillPaginate::ActionView::LinkRenderer) %>
    </div>

  </div>
</div>
<div class="row justify-content-center">
  <div class="col-sm-12 d-flex justify-content-center">
    <%= link_to 'Nuevo Entidad', new_company_path , class: "btn btn-primary mr-2" %>
  </div>
</div>

  <%= render "layouts/views_partials/button" %>
<% else %>
  <% route = "companies" %>
  <%= render "layouts/views_partials/not_found", route: route %>
<% end %>

app/views/companies/new.html.erb
<%  if current_user.role_id == User.ADMINISTRATOR  || current_user.role_id == User.EDITOR %>

  <div class="row">
    <div class="col-sm-10 offset-sm-1  text-center">
      <h3 class="my-4">Nueva compañia</h3>
    </div>
  </div>
  <%= render 'form', company: @company %>


<% else %>

  <% route = "companies" %>
  <%= render "layouts/views_partials/not_found", route: route %>
<% end %>

app/views/companies/show.html.erb
<div class="col-lg-8 offset-lg-2">
  <div class="card card-margin mt-4">
    <div class="card-header">
      <h5 class="card-title" style="display: inline-block">
        Datos compañia
      </h5>
      <% route = "companies" %>
      <%= render "layouts/views_partials/link_to_back_form_especial", route: route %>
    </div>

    <div class="card-body">
      <div class="table-responsive">
        <table class="table center-aligned-table table-striped">

          <tr>
            <th><strong>Identificacion:</strong></th>
            <td class="td-white"><%= @company.identification %></td>
          </tr>
          <tr>
            <th><strong>Nombre:</strong></th>
            <td class="td-white"><%= @company.name %></td>
          </tr>

          <tr>
            <th><strong>telefono:</strong></th>
            <td class="td-white"> <%= @company.phone %></td>
          </tr>

          <tr>
            <th><strong> Correo electronico:</strong></th>
            <td class="td-white"><%= @company.email %></td>
          </tr>

          <tr>
            <th><strong> Direccion:</strong></th>
            <td class="td-white"><%= @company.address %></td>
          </tr>

          <tr>
            <th><strong> Estado:</strong></th>
            <td>
              <% if  @company.enable %>
                Habilitado
              <% else %>
                inhabilitado
              <% end %>
            </td>
          </tr>









        </table>
      </div>
    </div>

    <div class="card-footer bg-white text-center">

      <%= link_to 'Editar', edit_company_path(@company) ,class: "btn btn-primary mr-2" %>
      <%= link_to 'Regresar', companies_path, class: "btn btn-light "  %>

    </div>
  </div>
</div>