config/routes.rb
Rails.application.routes.draw do






  mount ActionCable.server => '/cable'



  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  authenticated :user do
    get 'new_navigator' , to: "navigators#create_user" , as: 'create_navigator'
    post 'new_navigator' , to: "navigators#create_user"


  resources :conditions
  resources :lists
  resources :offers
  resources :students
  resources :users, except: [:show]
  resources :profiles , except: [:new,:edit,:show,:index]
  resources :engineers
  resources :areas
  resources :designations
  resources :modalities
  resources :companies
  resources :items
  resources :types
  resources :themes
  resources :concepts
  resources :responsible_functions
  resources :workers
  resources :admin_controls do
    resources :lists
    resources :checklists do
      resources :checklist_items
    end
  end

    get '/create_items', to: 'lists#create_items'
    post '/create_items' ,to: 'lists#create_items' , as: "create_lists"

    get '/destroy_engineer'  , to: 'designations#destroy_engineer' ,as: 'destroy_engineer'
    post '/destroy_engineer'  , to: 'designations#destroy_engineer'

    get '/destroy_support'  , to: 'admin_controls#destroy_support' ,as: 'destroy_support'
    post '/destroy_support'  , to: 'admin_controls#destroy_support'

    get '/destroy_manager'  , to: 'admin_controls#destroy_manager' ,as: 'destroy_manager'
    post '/destroy_manager'  , to: 'admin_controls#destroy_manager'

  resources :titles
  resources :universities
  resources :register_books
  get "/register_offer" , to: 'register_books#index_offer'  ,as: 'register_books_offer'


  resources :states do
    collection { post :import }
  end

  resources :cities do
    collection { post :import }
  end



  end

  get ":url" => "application#redirect_user", :constraints => { :url => /.*/ }

end

app/models/admin_control.rb
class AdminControl < ApplicationRecord
  scope :by_month, lambda {|date| where('start_date >= ? AND start_date <=  ?', date.beginning_of_month, date.end_of_month)}
  belongs_to :concept
  belongs_to :theme
  belongs_to :type
  belongs_to :item
  belongs_to :company
  belongs_to :city
  belongs_to :responsible_function
  belongs_to :user, optional: true

  has_many :checklists
  has_many :lists

  has_many :has_managers
  has_many  :workers, through: :has_managers
  serialize :has_managers
  attr_accessor :manager_elements


  has_many :has_supports
  has_many :workers, through: :has_supports
  serialize :has_supports
  attr_accessor :support_elements

  def save_supports

    if support_elements.present?
    support_elements.each do | support_id |
      support = HasSupport.find_or_create_by(admin_control_id: self.id, worker_id: support_id)
    end
    end
  end

  def save_managers
    if manager_elements.present?
      manager_elements.each do | manager_id|
        HasManager.find_or_create_by(admin_control_id: self.id, worker_id: manager_id)
      end
    end
  end

  after_create do
    RegisterBook.where(admin_control_id: self.id).update(code_sa: self.sa)
  end


  validates :company_id,:type_id,:theme_id,presence: true
  validates :concept_id, :city_id,:item_id,:responsible_function_id , presence: true
  validates :start_date,:final_date, presence: true
  validates :tracking_type,presence: true
  validates :state, presence: true


  has_rich_text :description_advance



  def self.TYPE_IPM
    1
  end
  def self.TYPE_PT
    2
  end

  def self.STATE_STOPPED
    1
  end
  def self.STATE_FINISH
    2
  end
  def self.IN_PROCESS
    3
  end



  def self.COMBO_TRACKING_TYPES
    [["IPM -Inmediato  Prioritario Mesa Tecnica",1],["PT - Progresivo Tranversal",2]]
  end

  def self.COMBO_STATES
    [["Detenido",1],["Terminado",2],["En Proceso",3]].sort
  end

end

app/controllers/admin_controls_controller.rb
class AdminControlsController < ApplicationController

  before_action :set_admin_control ,  only: [:show,:edit,:destroy,:update]
  include AdminControlsHelper
  include ComboBoxHelper
  include RegisterBooksHelper

  def index
    @responsible_functions = ResponsibleFunction.where(enable:true).map{|x| [x.name, x.id]}
    @months = (Date.today - 1.year..Date.today).map(&:beginning_of_month).uniq.reverse.map{|dt| [dt.strftime("%Y-%m"), dt] }
    @companies = Company.where(enable: true).order("name").map{|company| [company.name, company.id]}

    @search = if params[:search]
                Date.parse(params[:search])
              else
                Date.today
              end



    @company = params[:company] || " "
    @responsible = params[:responsible] || ""

    if @responsible != "" && @company != ""
      @admin_controls = AdminControl.all.joins(:company).where("lower(companies.name) like lower(?)","%#{@company}%")
                            .joins(:responsible_function).where("lower(responsible_functions.name) like lower(?)","%#{@responsible}%")
                            .by_month(@search)
                            .paginate(page: params[:page], per_page: 30).order('id desc')
    elsif @responsible != ""
      @admin_controls =  AdminControl.all.joins(:responsible_function).where("lower(responsible_functions.name) like lower(?)","%#{@responsible}%")
          .by_month(@search)
          .paginate(page: params[:page], per_page: 30).order('id desc')
    elsif @company != ""
      @admin_controls =  AdminControl.all.joins(:company).where("lower(companies.name) like lower(?)","%#{@company}%")
                .by_month(@search)
          .paginate(page: params[:page], per_page: 30).order('id desc')
    else
      @admin_controls = AdminControl.all.by_month(@search)
          .paginate(page: params[:page], per_page: 30).order('id desc')
    end


  end


  def show
    show_states
    percent_completed(@admin_control)
    show_tracking_type(@admin_control)
    show_state_admin_control(@admin_control)
    AdminControl.where(id:@admin_control.id).update(advance: percent_completed(@admin_control))
    ids =  HasSupport.where(admin_control_id: @admin_control.id).map{|x| x.worker_id}
    @support_has_name =  Worker.where(id:ids).map{|x| [x.full_name,x.id]}

    ids_manager =  HasManager.where(admin_control_id: @admin_control.id).map{|x| x.worker_id}
    @manager_has_name =  Worker.where(id:ids_manager).map{|x| [x.full_name,x.id]}
  end


  def new
    @admin_control = AdminControl.new
    combo_box_data
    worker_all
  end


  def edit
    worker_all
    combo_box_data
    percent_completed(@admin_control)
    ids =  HasSupport.where(admin_control_id: @admin_control.id).map{|x| x.worker_id}
    @support_has_name =  Worker.where(id:ids).map{|x| [x.full_name,x.id]}

    ids_manager =  HasManager.where(admin_control_id: @admin_control.id).map{|x| x.worker_id}
    @manager_has_name =  Worker.where(id:ids_manager).map{|x| [x.full_name,x.id]}
  end


  def create
    worker_all
    combo_box_data()

    @admin_control = AdminControl.new(admin_control_params)
    @admin_control.user_id = current_user.id
    @admin_control.support_elements = params[:support_elements]
    @admin_control.manager_elements = params[:manager_elements]
    @admin_control.advance = percent_completed(@admin_control)
      if @admin_control.save
        @admin_control.save_supports
        @admin_control.save_managers
        @admin_control.sa =  "sa-#{@admin_control.id}"
        @admin_control.save
        create_register_admin(@admin_control,current_user)
        # up_register =  RegisterBook.where(admin_control_id: @admin_control.id).update(code_sa: @admin_control.sa)
         redirect_to @admin_control, notice: "Segto Admin fue creado exitosamente."
      else
        combo_box_data()
         render :new, status: :unprocessable_entity

      end
  end


  def update
        worker_all
       combo_box_data()

      if @admin_control.update(admin_control_params)
        @admin_control.support_elements = params[:support_elements]
        @admin_control.manager_elements = params[:manager_elements]
        @admin_control.save_supports
        @admin_control.save_managers
        update_register_admin_control(@admin_control,current_user)
        redirect_to @admin_control, notice: "Segto Admin fue actualizado exitosamente."
      else

        combo_box_data()
      render :edit, status: :unprocessable_entity
      end

  end


  def destroy
    list = List.where(admin_control_id: @admin_control.id).delete_all
    HasManager.where(admin_control_id: @admin_control.id).delete_all
    HasSupport.where(admin_control_id: @admin_control.id).delete_all
    if destroy_register_admin_control(@admin_control,current_user)
        if delete_ref_admin_control(@admin_control)
           if @admin_control.destroy
              redirect_to admin_controls_url, notice: "Segto Admin fue destruido exitosamente."
           end
        end
    end

  end

  def percent_completed(admin_control)
    @total_items ||= admin_control.lists.count
    return 0 if @total_items == 0
    @percent_completed = ((admin_control.lists.select(&:completed?).count.to_f / @total_items) * 100).round
  end





  def destroy_support
    worker_id = params[:worker_id]
    admin_control_id = params[:admin_control_id]
    HasSupport.where(admin_control_id: admin_control_id).where(worker_id: worker_id).destroy_all
    redirect_to edit_admin_control_path(admin_control_id)
  end

  def destroy_manager
    worker_id = params[:worker_id]
    admin_control_id = params[:admin_control_id]
    HasManager.where(admin_control_id: admin_control_id).where(worker_id: worker_id).destroy_all
    redirect_to edit_admin_control_path(admin_control_id)
  end

  def create_register_admin(obj,current_user)
    register = RegisterBook.new(admin_control_id:obj.id,
                                create_user:"#{current_user.first_name}" + " " + "#{current_user.last_name}",
                                create_time:Date.today,offer_id: nil,
                                concept_admin: obj.concept.name,theme_admin:obj.theme.name,
                                type_admin:obj.type.name,item_admin: obj.type.name,company: obj.company.name,
                                code_sa: obj.sa,code: obj.code,rol_responsible: obj.responsible_function.name,is_admin_control:true )
    register.save
  end


  #Time.now.strftime("%I:%M:%S %P")
  def update_register_admin_control(obj,current_user)
    RegisterBook.where(admin_control_id:obj.id).update(update_user:"#{current_user.first_name}" + " " + "#{current_user.last_name}",
                                                       update_time:Date.today,
                                                       concept_admin: obj.concept.name,
                                                       theme_admin:obj.theme.name,
                                                       type_admin:obj.type.name,
                                                       item_admin: obj.item.name,
                                                       rol_responsible: obj.responsible_function.name,
                                                       code_sa: obj.sa,code: obj.code,
                                                       company:obj.company.name)
  end




  def destroy_register_admin_control(obj,current_user)
    @result = ""
    dia_actual = Date.today
    register = RegisterBook.where(admin_control_id:obj.id)
                   .update(destroy_user:"#{current_user.first_name}" + " " + "#{current_user.last_name}",
                           destroy_time: dia_actual,time_destroy:Time.now.strftime("%I:%M:%S %P"))
    if register
      @result = true
    else
      @result = false
    end
    return @result
  end

  def delete_ref_admin_control(obj)
    r = RegisterBook.where(admin_control_id: obj.id).update(admin_control_id: nil)
    if r
      result_admin = true
    else
      result_admin = false
    end
    return result_admin
  end


  private

  def show_states
    @status_checklist = ChecklistItem.STATUS_OPTIONS.map{|x| [x[0],x[1]]}
  end

  def combo_box_data
    generate_code()
    combo_box_general_data()
    combo_box_company()
    combo_box_personal()
  end

  def generate_code
     admin_control = AdminControl.all.map{|x| x.code}
     @suggest_code = admin_control.max == nil ? 1 : admin_control.max + 1
  end


    def set_admin_control
      @admin_control = AdminControl.find(params[:id])
    end


    def admin_control_params
      params.require(:admin_control).permit(:code,:concept_id,:theme_id,
                                            :type_id,:item_id,:start_date,:final_date,
                                            :tracking_type,:state,:company_id,:city_id,
                                            :responsible_function_id,:responsible,:support,
                                            :description_advance,:advance,:process,:link_process,:link_drive,:user_id,
                                            support_elements:[],manager_elements:[])
    end
end

app/helpers/admin_controls_helper.rb
module AdminControlsHelper

  def show_tracking_type(admin_control)
    if admin_control.tracking_type == AdminControl.TYPE_IPM
      @show_tracking_type = "IPM -Inmediato  Prioritario Mesa Tecnica"
    elsif admin_control.tracking_type == AdminControl.TYPE_PT
      @show_tracking_type = "PT - Progresivo Tranversal"
    elsif admin_control.tracking_type == "" || @admin_control.tracking_type == nil
      @show_tracking_type = "No tipo de seguimiento registrado"
    end
  end

  def show_responsible_and_support(admin_control)
    responsible = Worker.where(id: admin_control.responsible).map{ |w| [w.first_name,w.last_name]}
    if admin_control.responsible != nil && admin_control.responsible != ""
    @show_responsible = "#{responsible[0][0]} #{responsible[0][1]}"
    end
    if admin_control.support != nil && admin_control.support != ""
    support = Worker.where(id: admin_control.support).map{ |w| [w.first_name,w.last_name]}
    @show_support = "#{support[0][0]} #{support[0][1]}"
    end
  end



  def show_state_admin_control(admin_control)
    case admin_control.state
    when AdminControl.STATE_STOPPED
      return @show_state = "Detenido"
    when AdminControl.STATE_FINISH
      return @show_state = "Finalizado"
    when AdminControl.IN_PROCESS
      return @show_state = "En proceso"
    when nil
    return @show_state = "No tiene un estado asginado"
    when ""
      return @show_state = "No tiene un estado asginado"
    end
  end

  def enable_resources(admin_control,params)
    @enable = params[:enable]
    @enable ? admin_control.enable = @enable: admin_control.enable = false
  end


end

app/views/admin_controls/edit.html.erb
<%  if current_user.role_id == User.ADMINISTRATOR || @admin_control.user_id == current_user.id  || current_user.role_id == User.EDITOR %>
  <div class="row">
    <div class="col-sm-10 offset-sm-1 text-center">
      <h3 class="my-4">Editar Seguimiento Admin</h3>
    </div>
  </div>
<%= render 'form', admin_control: @admin_control %>
<% else %>
<% route = "admin_controls" %>
<%= render "layouts/views_partials/not_found", route: route %>
<% end %>

app/views/admin_controls/new.html.erb
<div class="row">
  <div class="col-sm-10 offset-sm-1 text-center">
    <h3 class="my-4">Nuevo Seguimiento Admin</h3>
  </div>
</div>


<%= render 'form', admin_control: @admin_control %>

app/views/admin_controls/show.html.erb
<div class="row">
  <div class="offset-sm-2 col-sm-8">
    <div class="card card-margin">


          <div id="accordion">


            <div class="card">
              <div class="card-header" id="headingThree">
                <h5 class="mb-0" style="display: inline-block" data-toggle="collapse" data-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
                  <a class="btn btn-link" data-toggle="collapse" data-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
                    Avances
                  </a>
                </h5>
                <% route = "admin_controls" %>
                <%= render "layouts/views_partials/link_to_back_form_especial" , route: route %>
              </div>

              <div id="collapseThree" class="collapse show" aria-labelledby="headingThree" data-parent="#accordion">


                <div class="card-body">
               <%  if current_user.role_id == User.ADMINISTRATOR || @admin_control.user_id == current_user.id  || current_user.role_id == User.EDITOR %>
                  <table class="table table-bordered">
                    <thead>

                    </thead>

                    <tbody>
                    <tr>
                      <td colspan="3">
                        <div class="progress">
                          <div class="progress-bar progress-bar-striped" role="progressbar" style="width: <%= @percent_completed %>%" aria-valuenow="<%= @percent_completed %>" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                      </td>
                    </tr>
                    <tr>

                      <td colspan="3">


                              <%= form_tag(:controller => "lists", :action => "create_items", :method => "get", local: true, class:"forms-sample form-inline") do %>
                          <a style="position: relative;top: 1px;" href="/admin_controls/<%= @admin_control.id %>/edit#list" class="btn btn-sm btn-outline-dark"><i class="fas fa-long-arrow-alt-left pd-y-5"></i></a>
                                <%= text_field_tag :description,"", class: "form-control" , style: 'width: 75%; display: inline-block; position:relative; top: 4px' %>
                                <%= hidden_field_tag :admin_control_id ,"#{@admin_control.id}" , class: "form-control" %>
                                <button type="submit" class="btn btn-outline-success mr-2 btn-action" style="width: 150px">Agregar tarea</button>

                              <% end %>
                      </td>
                    </tr>
                    <% @admin_control.lists.each do |list| %>
                      <% if list.completed %>
                        <tr class="table-secondary">
                          <td class="striker"><%= link_to  list.description,  edit_admin_control_list_path(@admin_control.id,list) %></td>
                          <td>
                            <%= form_with(model: [@admin_control,list]) do |f| %>
                              <%= f.text_field :admin_control_id,value: @admin_control.id , type: 'hidden' %>
                              <%= f.text_field :description , type: 'hidden' %>
                              <%= f.check_box :completed,:checked => false,:style => 'visibility: hidden' %>
                              <%= f.submit "Incompleto",class: 'btn btn-outline-secondary btn-sm' %>
                            <% end %>
                          </td>
                          <td>
                            <%= link_to "/admin_controls/#{@admin_control.id}/lists/#{list.id}",method: :delete, data: { confirm: '¿Esta seguro que desea eliminarlo?' } do   %>
                              <span class="btn btn-outline-danger"> <i class="fas fa-trash-alt"></i> </span>
                            <% end %>
                           </td>
                        </tr>
                      <% else %>
                        <tr>
                          <td><%= list.description %></td>
                          <td>
                            <%= form_with(model: [@admin_control,list], id:'form') do |f| %>
                              <%= f.text_field :admin_control_id,value: @admin_control.id , type: 'hidden' %>
                              <%= f.text_field :description , type: 'hidden' %>
                              <%= f.check_box :completed,:checked => true,:style => 'visibility: hidden' %>
                              <%= f.submit "Completar",class: 'btn btn-outline-secondary btn-sm' %>
                            <% end %>
                          </td>
                          <td>
                            <%= link_to "/admin_controls/#{@admin_control.id}/lists/#{list.id}",method: :delete, data: { confirm: '¿Esta seguro que desea eliminarlo?' } do   %>
                              <span class="btn btn-outline-danger"> <i class="fas fa-trash-alt"></i> </span>
                              <% end %>
                              </td>


                        </tr>

                      <% end %>

                    <% end %>
                    </tbody>
                  </table>

                <% else %>

                  <table class="table table-bordered" id="list">
                    <thead>
                    <tr>
                      <th colspan="2">
                        <span class="text-center">Lista de actividades</span>
                        <% if @admin_control.id? %>
                          <%= link_to admin_control_path(@admin_control.id) do %>
                                <span class="float-right btn  btn-outline-primary btn-sm">
                                <i class="far fa-plus-square"></i>
                                     </span>
                          <% end %>
                        <% end %>
                      </th>

                    </tr>
                    </thead>

                    <tbody>
                    <% @admin_control.lists.each do |list| %>
                      <tr>
                        <td style="width:50%; text-align: center"><%= list.description %></td>
                        <td style="width:50%; text-align: center">
                          <% if list.completed %>
                                     <span style="font-size: 15px" class="text-success">
                                    <i class="fas fa-check"></i>
                                     </span>
                          <% else %>
                                    <span style="font-size: 15px" class="text-danger">
                                       <i class="fas fa-times"></i>
                                    </span>
                          <% end %>
                        </td>
                      </tr>
                    <% end %>
                    </tbody>
                  </table>
                <% end %>
                </div>
                 </div>

            </div>



            <div class="card">
              <div class="card-header" id="headingOne">
                <h5 class="mb-0" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                  <a class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    Datos Generales
                  </a>
                </h5>
              </div>

              <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table center-aligned-table table-striped">

                      <tr>
                        <th class="bg-success text-light"><strong>Codigo</strong></th>
                        <td class="bg-success text-light"><%= @admin_control.code %></td>
                      </tr>

                      <tr>
                        <th><strong>Concepto</strong></th>
                        <td class="td-white"><%= @admin_control.concept.name %></td>
                      </tr>

                      <tr>
                        <th><strong>Asunto:</strong></th>
                        <td class="td-white"><%= @admin_control.theme.name %> </td>
                      </tr>

                      <tr>
                        <th><strong>Tipo:</strong></th>
                        <td class="td-white"><%= @admin_control.type.name %> </td>
                      </tr>


                      <tr>
                        <th><strong>Item Especifico:</strong></th>
                        <td class="td-white"><%= @admin_control.item.name %></td>
                      </tr>

                      <tr>
                        <th><strong>Fecha de inicio</strong></th>
                        <td class="td-white"><%= @admin_control.start_date %></td>
                      </tr>

                      <tr>
                        <th><strong>Fecha Final</strong></th>
                        <td class="td-white"><%= @admin_control.final_date %></td>
                      </tr>

                      <tr>
                        <th><strong>Tipo de seguimiento</strong></th>
                        <td class="td-white"><%= @show_tracking_type %></td>
                      </tr>


                      <tr>
                        <th><strong>Estado</strong></th>
                        <td class="td-white"><%= @show_state %></td>
                      </tr>

                      <tr>
                        <th><strong>Compañia</strong></th>
                        <td class="td-white"><%= @admin_control.company.name %> </td>
                      </tr>

                      <tr>
                        <th><strong>localizacion</strong></th>
                        <td class="td-white"><%= @admin_control.city.state.name %> - <%= @admin_control.city.name %> </td>
                      </tr>


                    </table>
                  </div>
                </div>
              </div>
            </div>



            <div class="card">
              <div class="card-header" id="headingTwo">
                <h5 class="mb-0" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                  <a class="btn btn-link" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                    Roles,estado e información adicional
                  </a>
                </h5>
              </div>

              <div id="collapseTwo" class="collapse show" aria-labelledby="headingTwo" data-parent="#accordion">
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table center-aligned-table table-striped">
                      <tr>
                        <th><strong>Rol Responsable</strong></th>
                        <td class="td-white"><%= @admin_control.responsible_function.name %></td>
                      </tr>
                      <tr>
                        <th><strong>Responsable</strong></th>
                        <td>
                          <ul style="list-style: none" class="text-center">
                            <% if @manager_has_name.present? %>
                            <% @manager_has_name.each  do |manager| %>
                              <li class="my-2" style="font-size: 14px; text-transform: capitalize; font-weight: 600">
                                <%= manager[0] %>
                              </li>
                            <% end %>
                              <% end %>
                          </ul>
                        </td>
                      </tr>
                      <tr>
                        <th><strong>Apoyo</strong></th>
                        <td>
                         <ul style="list-style: none" class="text-center">
                           <% @support_has_name.each  do |support| %>
                           <li class="my-2" style="font-size: 14px; text-transform: capitalize; font-weight: 600">
                             <%= support[0] %>
                           </li>
                           <% end %>
                         </ul>


                        </td>

                      </tr>

                      <tr>
                        <th><strong>Avance</strong></th>
                        <td class="td-white"><%=  @admin_control.advance %></td>
                      </tr>

                      <tr>
                        <th><strong>Proceso</strong></th>
                        <td><%= @admin_control.process %></td>
                      </tr>

                      <tr>
                        <th><strong>Descripcion del avance</strong></th>
                        <td><%= @admin_control.description_advance %></td>
                      </tr>

                      <tr>
                        <th><strong>Link del proceso</strong></th>
                        <td><%= @admin_control.link_process %></td>
                      </tr>

                      <tr>
                        <th><strong>Link del drive</strong></th>
                        <td><%= @admin_control.link_drive %></td>
                      </tr>




                    </table>
                  </div>
                </div>
                <div class="card-footer bg-white text-center">

                  <%= link_to 'Editar', edit_admin_control_path(@admin_control) ,class: "btn btn-primary mr-2" %>
                  <%= link_to 'Regresar', admin_controls_path, class: "btn btn-light "  %>

                </div>
              </div>
            </div>









          </div><!-- accordion -->



        </div>



    </div>
  </div>
  <div class="offset-sm-2"></div>
<%= render "layouts/views_partials/button" %>