config/routes.rb
Rails.application.routes.draw do






  mount ActionCable.server => '/cable'



  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  authenticated :user do
    get 'new_navigator' , to: "navigators#create_user" , as: 'create_navigator'
    post 'new_navigator' , to: "navigators#create_user"


  resources :conditions
  resources :lists
  resources :offers
  resources :students
  resources :users, except: [:show]
  resources :profiles , except: [:new,:edit,:show,:index]
  resources :engineers
  resources :areas
  resources :designations
  resources :modalities
  resources :companies
  resources :items
  resources :types
  resources :themes
  resources :concepts
  resources :responsible_functions
  resources :workers
  resources :admin_controls do
    resources :lists
    resources :checklists do
      resources :checklist_items
    end
  end

    get '/create_items', to: 'lists#create_items'
    post '/create_items' ,to: 'lists#create_items' , as: "create_lists"

    get '/destroy_engineer'  , to: 'designations#destroy_engineer' ,as: 'destroy_engineer'
    post '/destroy_engineer'  , to: 'designations#destroy_engineer'

    get '/destroy_support'  , to: 'admin_controls#destroy_support' ,as: 'destroy_support'
    post '/destroy_support'  , to: 'admin_controls#destroy_support'

    get '/destroy_manager'  , to: 'admin_controls#destroy_manager' ,as: 'destroy_manager'
    post '/destroy_manager'  , to: 'admin_controls#destroy_manager'

  resources :titles
  resources :universities
  resources :register_books
  get "/register_offer" , to: 'register_books#index_offer'  ,as: 'register_books_offer'


  resources :states do
    collection { post :import }
  end

  resources :cities do
    collection { post :import }
  end



  end

  get ":url" => "application#redirect_user", :constraints => { :url => /.*/ }

end

app/models/area.rb
class Area < ApplicationRecord
end

app/models/checklist.rb
class Checklist < ApplicationRecord
  belongs_to :admin_control
  has_many :checklist_items , dependent: :destroy


  def new_item
   checklist_items.build
  end

  def percent_complete
    #return 0 #if total_items == 0
    #((checklist_items.select(&:complete?).count.to_f / total_items)*100).round
  end
  def percent_in_progress
    50
  end

  def total_items
    @total_items ||= checklist_items.count
  end

end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
  require 'csv'
  def  self.import(file)
    CSV.foreach(file.path, headers:true) do |row|
      City.create! row.to_hash
    end
  end
end

app/models/company.rb
class Company < ApplicationRecord
  validates :name, presence: true
  validates :identification, presence: true , numericality: true
  validates :phone, presence: true
  validates :address, presence: true
  validates :email, presence: true ,  format: { with: /\A\S+@.+\.\S+\z/ ,message: "Direccion valida con @" }
end

app/models/concept.rb
class Concept < ApplicationRecord
  validates  :name, presence: true
end

app/models/condition.rb
class Condition < ApplicationRecord
end

app/models/engineer.rb
class Engineer < ApplicationRecord
  belongs_to :profile
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name , presence: true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :admin_control


  def completed?
    completed == true
  end
end

app/models/modality.rb
class Modality < ApplicationRecord
  validates :name,:description,presence: true

end

app/models/offer.rb
class Offer < ApplicationRecord
  scope :by_month, lambda {|date| where('publication_date >= ? AND publication_date <=  ?', date.beginning_of_month, date.end_of_month)}
  belongs_to :worker
  belongs_to :modality
  belongs_to :city, optional: true
  belongs_to :company, optional: true
  belongs_to :user


  validates :code,:worker_id,:modality_id, :status, :publication_date, presence: true
  validates :date_submission_obs, :date_offer_evaluation_report,:date_deadline_submission_offers,
            :date_obs_offer_evaluation_report,:date_publication_observations_report,:date_acceptance_offers,presence: true
  validates :status_obs_offer_evaluation_report,:status_offer_evaluation_report,:status_obs_report,
            :status_acceptance_offers,:status_submission_offers,:status_obs , presence: true
  validates :presented_value,:budget_value, :company_id, :city_id, :official_page,:email_company,
            :email_alternative,:link_document,presence: true

  #solo date y status
  has_rich_text :object



  def self.STATUS
    [["En proceso","En proceso"],["Descartado","Descartado"],["Adjudicado","Adjudicado"],["Entregado","Entregado"]].sort
  end

  def self.STATUS_YES_OR_NOT
    [["Si","Si"],["No","No"]]
  end






end

app/models/process.rb
class Process < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :name, presence: true
  validates :profile_type, presence: true

  def self.PROFILE_TYPE
    [["Lider",1],["Ingeniero Encargado",2],["Ingeniero acompañante",3],
     ["Responsable",4],["Apoyo",5],["Comodin",6],
     ["Practicante",7],["Empleado",8],["Ingeniero",9]]
  end


  def self.PROFILE_LEADER
    1
  end
  def self.PROFILE_ENGINEER_IN_CHARGE
    2
  end
  def self.PROFILE_ENGINEER_ATTENDANT
    3
  end
  def self.RESPONSIBLE
    4
  end
  def self.SUPPORT
    5
  end
  def self.WILDCARD
    6
  end
  def self.INTERN
    7
  end
  def self.EMPLOYEE
    8
  end
  def self.ENGINEER
    9
  end


end

app/models/state.rb
class State < ApplicationRecord
  require 'csv'
  def  self.import(file)
    CSV.foreach(file.path, headers:true) do |row|
      State.create! row.to_hash
    end
  end

end

app/models/student.rb
class Student < ApplicationRecord


  belongs_to :condition
  belongs_to :type_identification
  belongs_to :city
  belongs_to :university
  belongs_to :title
=begin



  belongs_to :title



  validates :name, :last_name,:phone,:address,:score,:semester,presence:true
  validates :semester,:career,:comment,:age,:birthday, presence:true
  validates :link_data,:issued_in,:link_university ,presence:true
  validates :leader_first,:leader_second, presence: true
  validates :identification,presence: true,numericality: true
  validates :mail, presence: true , format: { with: /\A\S+@.+\.\S+\z/ ,message: "Direccion valida con @" }

=end
  has_rich_text :body_1
  has_rich_text :body_2


end

app/models/theme.rb
class Theme < ApplicationRecord
  validates :name, presence: true
end

app/models/title.rb
class Title < ApplicationRecord
end

app/models/type.rb
class Type < ApplicationRecord
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  def self.ADMINISTRATOR
    1
  end
  def self.EDITOR
    2
  end
  def self.AUTHOR
    3
  end

  def show_name_role(role)
    if role == User.ADMINISTRATOR
      "Administrador"
    elsif role == User.EDITOR
      "Editor"
    elsif role == User.AUTHOR
      "Usuario"
    end
  end


  def destroy
    update_attributes(deactivated: true) unless deactivated
  end

  def active_for_authentication?
    super && !deactivated
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


end

app/models/worker.rb
class Worker < ApplicationRecord

  belongs_to :type_identification

  validates :first_name,:last_name,:phone,:phone_2, presence: true
  validates :identification, presence: true,numericality: true
  validates :type_identification_id, presence: true
  validates :email, presence: true ,  format: { with: /\A\S+@.+\.\S+\z/ ,message: "Direccion valida con @" }

  has_rich_text :function

  def full_name
    self.first_name + " " + self .last_name
  end

  def self.CHARACTERISTIC_TWO
    0
  end
  def self.CHARACTERISTIC_THREE
    1
  end
  def self.CHARACTERISTIC_FOUR
    2
  end
end

app/helpers/states_students_helper.rb
module StatesStudentsHelper
end

app/views/states_students/_form.html.erb
<div class="row">
  <div class="offset-sm-1 col-sm-10 ">
    <div class="card card-margin">

      <div class="card-header">
        <% route = "states_students" %>
        <%= render "layouts/views_partials/link_to_back", route: route %>
      </div>

      <%= bootstrap_form_with(model: states_student, local: true, html: { class: "forms-sample needs-validation", novalidate: true }) do |form| %>
        <div class="card-body">
          <% if states_student.errors.any? %>
            <div id="error_explanation" style="display: none">
              <h2><%= pluralize(states_student.errors.count, "error") %> prohibited this states_student from being saved:</h2>

              <ul>
                <% states_student.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
<div class="row no-gutters">
  <div class="col-sm-10 pr-2">
    <div class="form-group">
      <%= form.text_field :name, label: t('states_students.name') ,class: "form-control" , required: true %>
    </div>
  </div>
 <div class="col-sm-2">
   <div class="form-group">
    <%= form.color_field :color, label: t('states_students.color'), class: 'form-control', required: true %>
  </div>
 </div>
</div>


          <% if @states_student.id? %>
            <div class="form-group">
              <h4><%= t('commons.disabled&enabled') %></h4>
              <label class="switch">
                <input type="checkbox" name="enable" id="enable" value="true" <%= @states_student.enable ? "checked='checked'":""%> >
                <span class="slider round"></span>
              </label>
            </div>
          <% end %>




        </div>

        <div class="card-footer bg-white">
          <button type="submit" class="btn btn-primary mr-2 btn-action">Guardar</button>
          <%= link_to 'Regresar', states_students_path ,class: "btn btn-light btn-action"  %>


        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/states_students/edit.html.erb
<% if current_user.role_id == User.ADMINISTRATOR  || current_user.role_id == User.EDITOR %>
<div class="row">
  <div class="col-sm-10 offset-sm-1 text-center">
    <h3 class="my-4">Editar Estado</h3>
  </div>
</div>

<%= render 'form', states_student: @states_student %>
<% else %>

  <% route = "states_students" %>
  <%= render "layouts/views_partials/not_found", route: route %>

<% end %>

app/views/states_students/index.html.erb
<% if current_user.role_id == User.ADMINISTRATOR  || current_user.role_id == User.EDITOR %>
<div class="row">
  <div class="col-md-10 offset-md-1  text-center">
    <h2 class="my-4"><%= t('states_students.states_students') %></h2>
  </div>
</div>
<div class="row">
  <div class="offset-sm-1 col-sm-10">
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
        <tr class="text-center">
          <th scope="col">#</th>
          <th scope="col">Nombres</th>
          <th scope="col" class="text-center">Color</th>
          <th scope="col">Estado</th>
          <th colspan="2"></th>
        </tr>
        </thead>

        <tbody>
        <% @states_students.each_with_index  do |state_student, index | %>

          <tr class="text-center">
            <td> <%= index + 1  %></td>
            <td><%= state_student.name %> </td>
            <td class="text-center"> <div style="position:relative; margin: auto;  width: 40px; height: 20px;background-color: <%= state_student.color %>"></div></td>
            <td>
              <% if  state_student.enable %>
                Habilitado
              <% else %>
                Deshabilitado
              <% end %>

            </td>
            <td>
              <% if current_user.role_id == User.ADMINISTRATOR  || current_user.role_id == User.EDITOR %>
                  <%= link_to  edit_states_student_path(state_student) do %>
                     <%= @show_edit %>
                  <% end %>
               <% end %>
              <% if current_user.role_id == User.ADMINISTRATOR  %>
                   <%= link_to  state_student, method: :delete, data: { confirm: '¿Esta seguro que desea eliminarlo?' } do %>
                   <%= @show_trash %>
                   <% end %>
                <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>

      <br>
    </div>
  </div>

  <div class="will_paginate">
    <%= will_paginate(@states_students, :renderer => WillPaginate::ActionView::LinkRenderer) %>
  </div>

</div>
<div class="row justify-content-center">
  <div class="col-lg-12 d-flex justify-content-center">
    <%= link_to "Nuevo #{t('states_students.states_students')}", new_states_student_path , class: "btn btn-primary mr-2" %>
  </div>



</div>

<%= render "layouts/views_partials/button" %>
<% else %>
  <% route = "states_students" %>
  <%= render "layouts/views_partials/not_found", route: route %>
<% end %>

app/views/states_students/new.html.erb
<% if current_user.role_id == User.ADMINISTRATOR  || current_user.role_id == User.EDITOR %>
<div class="row">
  <div class="col-sm-10 offset-sm-1 text-center">
    <h3 class="my-4">Nuevo Estado</h3>
  </div>
</div>

<%= render 'form', states_student: @states_student %>

<% else %>
  <% route = "states_students" %>
  <%= render "layouts/views_partials/not_found", route: route %>
<% end %>